plugins {
    id 'com.android.application' version '8.5.2' apply false
    id 'java-library' apply false
}

ext {
    appName = 'GMC-GAME'
    gdxVersion = '1.12.1'
    gamesvcsVersion = '1.2.0'
    cuVersion = '2.3.0'
    oneSignalSdkVersion = '4.8.6'
    retrofitVersion = '2.11.0'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
