plugins {
    id 'com.android.application'
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.15.4'
}

android {
    namespace 'ir.vahidhoseini.gmc.android'
    compileSdk 36

    defaultConfig {
        applicationId "ir.vahidhoseini.gmc.android"
        manifestPlaceholders = [
                onesignal_app_id               : '0d2b8789-ee3d-41de-beef-fe1ec429a4b8',
                onesignal_google_project_number: 'REMOTE'
        ]
        versionCode 14
        versionName "1.0.4"
        minSdk 24
        targetSdk 36
        buildConfigField "String", "TAPSELL_KEY", "\"ejmrmnkrordhtfbfktqgsroedmcghrdjakkfiadigktlfnabimsjatdmjrqehdkigmtjkk\""
        buildConfigField "String", "TAPSELL_INTERSTITIAL_BANNER", "\"5ea0d518987f4600015d4ed4\""
        buildConfigField "String", "TAPSELL_REWARDED_Video", "\"5e8507458d46ea0001154637\""
        buildConfigField "String", "app_management", "\"https://vahidhoseini.ir/apps/\""
        buildConfigField "String", "app_management_file", "\"update-message-GMC-Android-2226105219165086.json\""
        buildConfigField "String", "ONE_SIGNAL_APP_ID", "\"0d2b8789-ee3d-41de-beef-fe1ec429a4b8\""
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }
    }

    signingConfigs {
        release {
            storeFile = file("/home/pedja/keystore.jks")
            storePassword = System.getenv("KEYSTORE_PWD")
            keyAlias = System.getenv("KEYSTORE_ALIAS")
            keyPassword = System.getenv("KEYSTORE_ALIAS_PWD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkAllWarnings false
        checkReleaseBuilds false
        quiet true
    }
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
    implementation "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-controllers-android:$gdxVersion"

    implementation 'ir.tapsell.plus:tapsell-plus-sdk-android:1.1.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "com.onesignal:OneSignal:$oneSignalSdkVersion"
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'com.pushpole.android:pushsdk:1.7.0'
}
